"""users table

Revision ID: 44adae75228d
Revises: 009b555d65ff
Create Date: 2019-05-24 12:00:26.483818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44adae75228d'
down_revision = '009b555d65ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('r_count', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'url', ['short_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url', type_='unique')
    op.drop_column('url', 'r_count')
    # ### end Alembic commands ###
